### ISSUE TITLE
Forcing Evaluation of an AST

### ISSUE THREAD

**Issue by crockeea** [emilaxelsson/syntactic#21]
What's the best way to force evaluation of an AST? I tried to define an `NFData` instance (from [Control.Deepseq](https://hackage.haskell.org/package/deepseq)) for `AST dom a`, but the existential types in the constructors cause problems. Is there any hope for an `NFData` instance? What about other ways to ensure that the tree is fully evaluated?

**Comment by emilaxelsson** [comment]
I think you just need an extra class for forcing symbols:

~~~~~~~~~~~~~~~~~~~~{.haskell}
class NFSym sym
  where
    rnfSym :: sym sig -> ()

instance NFSym sym => NFData (AST sym sig)
  where
    rnf (Sym s)  = rnfSym s
    rnf (s :$ a) = rnf s `seq` rnf a
~~~~~~~~~~~~~~~~~~~~
