### ISSUE TITLE
Codensity monad

### ISSUE THREAD

**Issue by Icelandjack** [emilaxelsson/syntactic#29]
The paper Combining Deep and Shallow Embedding of Domain-Specific Languages says about this “Readers with prior knowledge about monads will recognize that Mon is similar to the continuation passing monad. The difference is that the answer type has been specialized to generate syntax trees.” 

```
data Mon m a = M { unM :: forall b. ((a → FunC (m b)) → FunC (m b)) }
```

This is actually the [`Codensity`](https://hackage.haskell.org/package/kan-extensions-5.0.1/docs/Control-Monad-Codensity.html) monad.

```haskell
type Codensity m a = forall b. (a -> m b) -> m b
```

**Comment by emilaxelsson** [comment]
Yes, thanks, we're aware of this. Should probably have commented on that in the journal version of the paper.

I'll add a comment in the source code.
