### ISSUE TITLE
package not on stackage

### ISSUE THREAD

**Issue by MarisaKirisame** [emilaxelsson/syntactic#37]
Hi, can you get this package on stackage? I am using stack and want to use it.

**Comment by emilaxelsson** [comment]
Hi! That might be a good idea. But I'm currently going through a period in which I have no time to work on any of my packages. If you think it's worthwhile, would you be able to check what it would take to make it happen? If not, hopefully you can get by by declaring Syntactic as an extra dependency. I did put in some work earlier this year to make sure it builds with the latest everything.
